version: "3.8"

services:
  db:
    image: postgres
    env_file: postgres.env
    volumes:
      - "db_data:/var/lib/postgresql/data"
    ports:
      - 2345:5432
  web:
    image: allizon/ts-server
    volumes:
      - type: bind
        source: /Users/alholt/code/ts-server
        target: /app
    ports:
      - 8080:3000

volumes:
  db_data:
  web_data:
